### PR TITLE
Email communication with landlord

### LINKED ISSUE #197: Communication with landlord
**Is your feature request related to a problem? Please describe.**

When I make maintenance issues on this app I want my landlord to be aware immediately to action this. As such sending a notification would be very useful.

**Describe the solution you'd like**

Every time issues are created or edited/updated I want an email sent to the landlord notifying them of the issue and it's the description. This should be sent through the front end using emailJS.

**Describe alternatives you've considered**

SendGrid could have been implemented on the backend but requires considerably more dev time and we do not have any devs with familiarity. This could be a simple notification but if the landlord does not have the app open then they will not see it, in contrast, an email is a reliable and traditional method of communication.

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

### PR DESCRIPTION
**Pull request by butterplup**
# Description

Note: added dependency for @emailjs/browser, and `REACT_APP_EMAILJS_USER_ID` to the .env files in the frontend package.

Now when issues are created or edited an email is sent to the landlord notifying them of this.

Fixes/resolves #197

## Screenshots

Email template:
Email Template

## Type of change

Please delete options that are not relevant.

- [x] **New feature** (non-breaking change which adds functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] This change requires a documentation update

# Checklist:

Leave blank if not applicable

I have completed these steps when making this pull request:

- [x] I have assigned my name to the issue
- [x] I have moved the issue to the **In Progress** column
- [x] I have labelled the PR appropriately
- [x] I have assigned myself to the PR

Before opening the PR for review:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added attributions to new dependencies and resources
- [x] I have moved the linked issue to the **Review in Progress** column

### CODE REVIEW

**Review by lin8231 — DISMISSED** [review]
This looks really great! Loving seeing it in action.

**Review by noahjade — DISMISSED** [review]
So cool 🤩 Thanks so much for this its such a cool feature to get in!! Enjoy being spammed by bots tho with that secret key push uh oh

**Review by noahjade — APPROVED** [review]
Fixed up the dependency issue! This is great work thanks for making it!

**Review by lanxdrey19 — APPROVED** [review]
LGTM

**Pull request merged**
