### PR TITLE
Change firebase.json path location, update .gitattributes

### LINKED ISSUE #108: Invalid firebase.json path
**Describe the bug**

fIrebase.json has been changed to an invalid path

**To Reproduce**

1. Start the application and see the application fail to start because of an invalid firebase.json patrh

**Expected behavior**

The application should start

**Desktop (please complete the following information):**

 - OS: Ubuntu

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. bug, front-end, back-end).
- [x] I have added the **Platform Project** project

### PR DESCRIPTION
**Pull request by fishmonger45**
# Description

Change firebase.json to correct location, license is autocollapsed in github diff
fixes #108 

# Fixes
- [x] **Bug fix** (non-breaking change which fixes an issue)

I have completed these steps when making this pull request:

- [ ] I have assigned my name to the issue
- [ ] I have moved the issue to the **In Progress** column
- [ ] I have labelled the PR appropriately
- [ ] I have assigned myself to the PR

Before opening the PR for review:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added attributions to new dependencies and resources
- [ ] I have moved the linked issue to the **Review in Progress** column

### CODE REVIEW

**Comment by fishmonger45** [comment]
Why is the lockfile/husky changing? I haven't made any changes to this. Just so much 'magic' going on with this tooling.

**Review by j-chad — APPROVED** [review]
LGTM

**Comment by j-chad** [comment]
> Why is the lockfile/husky changing? I haven't made any changes to this. Just so much 'magic' going on with this tooling.

mine has been doing the same

**Comment by j-chad** [comment]
also please go through PR checklist before merging. You will also need to create a bug report.

**Comment by frasermcc9** [comment]
Looks like the linter is just surrounding a path in quotes for the shell scripts in husky

**Review by brookeknowles — APPROVED** [review]

**Pull request merged**
