### PR TITLE
Add Corner Alert

### LINKED ISSUE #55: FE Useful Components - Corner Alerts
**Is your feature request related to a problem? Please describe.**
Often we want to use components like toasts to respond to user actions, to acknowledge that something is happened. It would be useful to have an easy-to-use component API to allow for this.

**Describe the solution you'd like**
A toast/corner alert, callable via a easy function or hook.

### Checklist:

- [X] I have double checked that the issue does not currently exist. 
- [X] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [X] I have added the **Platform Project** project

### PR DESCRIPTION
**Pull request by frasermcc9**
# Description
Add toast-like component.

## Example usage:
```tsx
const { createAlert } = useAlert();
const createWarning = () =>
  createAlert(
    {
      icon: <ExclamationCircleIcon />,
      message: 'Uploading image of your bill...',
      mode: 'info',
    },
    3000,
  );

return <button onClick={createWarning}>Click Me</button>;
```

## Result
image

Fixes/resolves #55 

## Screenshots
Please include any screenshots or media that illustrates the changes made

## Type of change
Please delete options that are not relevant.

- [X] **New feature** (non-breaking change which adds functionality)

# Checklist:
Leave blank if not applicable

I have completed these steps when making this pull request:
- [x] I have assigned my name to the issue
- [x] I have moved the issue to the **In Progress** column
- [x] I have labelled the PR appropriately
- [x] I have assigned myself to the PR

Before opening the PR for review:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have moved the linked issue to the **Review in Progress** column

### CODE REVIEW

**Review by FriedhelmWS — COMMENTED** [review]
LGTM!

**Comment by j-chad** [comment]
idk if you noticed but this is on the upstream repo

**Comment by frasermcc9** [comment]
> idk if you noticed but this is on the upstream repo

Yeah this is just adding a component that I imagine will be useful in the future.

**Comment by j-chad** [comment]
> Yeah this is just adding a component that I imagine will be useful in the future.

I meant that this branch wasnt created on your fork. No big deal, just letting you know 🙂

**Comment by frasermcc9** [comment]
> > Yeah this is just adding a component that I imagine will be useful in the future.
> 
> I meant that this branch wasnt created on your fork. No big deal, just letting you know 🙂

ah I must have set the wrong origin URL when switching computers

**Pull request closed without merging**
