### PR TITLE
Implement Manage Flat Page

### LINKED ISSUE #170: Manage flat page
**Is your feature request related to a problem? Please describe.**

It would be useful to have a manage flat page to keep track of flat details, such as total rent, owner contact number, its occupants and their information, their rent split, etc. The owner should have edit access, while everyone else has read access.

**Describe the solution you'd like**

Implement a manage flat page, using the #153 component and #152 component. Additionally, new API calls are needed and schemas need to be updated. 

**Describe alternatives you've considered**

n/a 
Team decided that this is the best solution

**Additional context**

 Mockups by @rainasong 
image

image

### Checklist:

- [ ] I have double checked that the issue does not currently exist. 
- [ ] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [ ] I have added the **Platform Project** project
- [ ] I have implemented the correct API calls
- [ ] I have updated types/schemas correspondingly 
- [ ] The page is responsive 
- [ ] The owner is able to edit 
- [ ] Other members are only able to read
- [ ] Sections are displayed with the correct titles

### PR DESCRIPTION
**Pull request by lin8231**
# Description

We needed a manage flat page so that the occupants can see any shared information about the flat, including total rent, owner contact, etc. Each occupant should also be listed along with their information. 
This page is fully done

New API calls are added
Also changed the type of rent and maxOccupants the backend string -> number
Updated a few minor things for OccupantsPanel/Card and HouseSettings
Added routing

A new issue may add loading states/error handling in the future if necessary 

Fixes/resolves #170 

## Screenshots

image

## Type of change

Please delete options that are not relevant.

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

Leave blank if not applicable

I have completed these steps when making this pull request:

- [x] I have assigned my name to the issue
- [x] I have moved the issue to the **In Progress** column
- [x] I have labelled the PR appropriately
- [x] I have assigned myself to the PR

Before opening the PR for review:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have added attributions to new dependencies and resources
- [x] I have moved the linked issue to the **Review in Progress** column

### CODE REVIEW

**Review by hajineats — DISMISSED** [review]
Looking good! Thanks for this

**Review by AdamAWiener — DISMISSED** [review]
Looks great! Thanks for tying everything together so nicely!

**Review by scorpionknifes — COMMENTED** [review]
Looks great! Noice Git History btw

**Review by jimwang6012 — DISMISSED** [review]
LGTM!

**Review by rainasong — APPROVED** [review]
Looks awesome! Thanks so much for your hard work!!

**Review by sydive — APPROVED** [review]
LGTM! Thanks for this!

**Pull request merged**
