### PR TITLE
add attribution files for the 3rd party dependencies and other resources (new PR)

### LINKED ISSUE #43: dependency license checking
**Is your feature request related to a problem? Please describe.**
We need to check all the licenses of our dependencies to ensure they are compatible with our project

**Describe the solution you'd like**
We need to go through each dependency and check if we are able to use it, and if so are there any conditions to use?
We may have to add an attribution section to our app. Potentially could also attribute in the wiki but unsure

Also should add a check in the PR checklist to add any attribution required

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

### PR DESCRIPTION
**Pull request by wshe874**
# Description

- Adding attributions to 3rd party dependencies and other resources used in the project
- Adding scripts to automate the attribution generation

Fixes/resolves #43

## Screenshots
Please include any screenshots or media that illustrates the changes made

## Type of change
Please delete options that are not relevant.

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:
Leave blank if not applicable

I have completed these steps when making this pull request:
- [x] I have assigned my name to the issue
- [x] I have moved the issue to the **In Progress** column
- [x] I have labelled the PR appropriately
- [x] I have assigned myself to the PR

Before opening the PR for review:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have moved the linked issue to the **Review in Progress** column

### CODE REVIEW

**Comment by j-chad** [comment]
Previously #57

**Comment by j-chad** [comment]
@wshe874 please go through the checklist

**Comment by wshe874** [comment]
> @wshe874 please go through the checklist

Thanks for the reminder, I have went through the checklist.

**Review by mped822 — DISMISSED** [review]
lgtm

**Comment by alyu201** [comment]
LGTM

**Review by alyu201 — DISMISSED** [review]
LGTM

**Review by mped822 — DISMISSED** [review]

**Review by mped822 — APPROVED** [review]

**Review by alyu201 — APPROVED** [review]

**Pull request merged**
