### PR TITLE
Implemented PUT /api/v1/house/update and various bug fixes

### LINKED ISSUE #144: Implement PUT /house/update endpoint
**Is your feature request related to a problem? Please describe.**

Implement `PUT /api/v1/house/update` endpoint to update house information when the house configuration is changed and saved. 

**Describe the solution you'd like**

- [x] Create a new controller in `house.controller.ts` for the new endpoint
- [x] Update the house schema in `house.schema.ts` to accommodate for the newly added configuration properties
- [x] Update the `GET /api/v1/house` endpoint and DTO to return the newly added configuration properties
- [ ] ~~Change the `update` service in `houseStore.service.ts` to update the new configuration properties in the database (***may not need to***)~~

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

### LINKED ISSUE #150: `GET /api/v1/house` returns the wrong owner id
**Describe the bug**

The `GET /api/v1/house` endpoint always returns the requesting user's id in the owner field instead of the actual owner's id. 

**To Reproduce**

1. Create a new account and create a flat
2. Create a second account and join the flat created in step 1
3. Open dev tools on the second account
4. Check the `owner` field in the response body, the `owner` field matches the second account when it should be the first

**Expected behavior**

The `owner` field returned in the response body should be the house owner's `firebaseId`. 

**Screenshots**

n/a

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: Chrome
 - Version: 99

**Additional context**

n/a

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. bug, front-end, back-end).
- [x] I have added the **Platform Project** project

### PR DESCRIPTION
**Pull request by jimwang6012**
# Description

- Implemented the `PUT /api/v1/house/update` endpoint and its related services. This endpoint allows the house information to be updated when the house configuration is changed and saved on frontend. 
- Fixed a bug in the `GET /api/v1/house` endpoint where the requesting user's ID would be returned in the `owner` field instead of the actual owner's. 

Fixes: #144, #150 

## Screenshots

n/a

## Type of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)

# Checklist:

Leave blank if not applicable

I have completed these steps when making this pull request:

- [x] I have assigned my name to the issue
- [x] I have moved the issue to the **In Progress** column
- [x] I have labelled the PR appropriately
- [x] I have assigned myself to the PR

Before opening the PR for review:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have moved the linked issue to the **Review in Progress** column

### CODE REVIEW

**Comment by rainasong** [comment]
LGTM! I just merged the user endpoint changes, do you want to add new user fields for the users list in the house model in this PR as well?

**Comment by jimwang6012** [comment]
> LGTM! I just merged the user endpoint changes, do you want to add new user fields for the users list in the house model in this PR as well?

Added!

**Review by butterplup — APPROVED** [review]
LGTM 😎

**Review by rainasong — APPROVED** [review]
Looks nice! Thanks so much for your hard work!!

**Pull request merged**
