### PR TITLE
Add auth emulator

### LINKED ISSUE #123: Use auth emulator
**Is your feature request related to a problem? Please describe.**
Using our staging/production auth service during development means it gets spammed with random data. We should add an auth emulator so the service can be abused as much as desired without impacting 3rd party services.

**Describe the solution you'd like**
Setup firebase emulators.

### Checklist:

- [x] I have double checked that the issue does not currently exist. 
- [x] I have added the appropriate labels (e.g. feature, front-end, back-end).
- [x] I have added the **Platform Project** project

### PR DESCRIPTION
**Pull request by frasermcc9**
# Description

Sets up the firebase auth emulator, which allows us to locally use auth services without effecting the prod auth service. Especially useful during tests so the service isn't spammed with random accounts.

Fixes/resolves #123 

Should be merged before #94 

## Type of change

- [x] **New feature** (non-breaking change which adds functionality)

# Checklist:

Leave blank if not applicable

I have completed these steps when making this pull request:

- [x] I have assigned my name to the issue
- [x] I have moved the issue to the **In Progress** column
- [x] I have labelled the PR appropriately
- [x] I have assigned myself to the PR

Before opening the PR for review:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added attributions to new dependencies and resources
- [x] I have moved the linked issue to the **Review in Progress** column

### CODE REVIEW

**Review by fishmonger45 — DISMISSED** [review]
Everything works fine when I have tried this locally, but my review should be cheapened my inexperience with this. All the new users were tracked in the auth UI fine

**Comment by frasermcc9** [comment]
> Everything works fine when I have tried this locally, but my review should be cheapened my inexperience with this

That probably makes it better since it worked with no extra setup :P

**Comment by fishmonger45** [comment]
Maybe just add the emulator ui `http://localhost:4000/auth` to the appropriate readme? Probably not needed given it's a giant banner in stdout

**Review by fishmonger45 — DISMISSED** [review]

**Review by alyu201 — DISMISSED** [review]

**Review by fishmonger45 — DISMISSED** [review]

**Review by fishmonger45 — DISMISSED** [review]

**Review by alyu201 — DISMISSED** [review]

**Review by j-chad — APPROVED** [review]
LGTM

**Review by fishmonger45 — APPROVED** [review]
not many eggs left to break.

**Pull request merged**
